### ISSUE TITLE
_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

### ISSUE THREAD

**Issue by YisuZhou** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#11]
0\ use Xshell connect my dev machine 
1\ setup my env following https://github.com/open-mmlab/mmsegmentation/blob/83d312e87a805050bc52d51165e5a332f1ff84fb/docs/get_started.md
2\ check version: python3.7, mmcv-full 1.3.0, torch 1.6.0
3\ run code: python3 demo/image_demo.py data/infer/images/test/dataset10k_9684.jpg configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k.py ../upernet_swin_base_patch4_window7_512x512.pth

 
Traceback (most recent call last):
  File "demo/image_demo.py", line 3, in <module>
    from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/users/xxx/swin-trans/Swin-Transformer-Semantic-Segmentation-main/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/users/xxx/swin-trans/Swin-Transformer-Semantic-Segmentation-main/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/users/xxx/swin-trans/Swin-Transformer-Semantic-Segmentation-main/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/users/xxx/swin-trans/Swin-Transformer-Semantic-Segmentation-main/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/users/xxx/swin-trans/Swin-Transformer-Semantic-Segmentation-main/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/users/xxx/swin-trans/Swin-Transformer-Semantic-Segmentation-main/mmseg/models/decode_heads/__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "/home/users/xxx/swin-trans/Swin-Transformer-Semantic-Segmentation-main/mmseg/models/decode_heads/cc_head.py", line 7, in <module>
    from mmcv.ops import CrissCrossAttention
  File "/home/users/xxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/users/xxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/users/xxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/users/xxx/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/users/xxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

Something went wrong, but I have no idea...

**Comment by Lature-Yang** [comment]
Have you tried the 1.2.4 version of mmcv-full? Maybe the version is too high.

**Comment by YisuZhou** [comment]
I uninstalled v1.3.0 and installed v1.2.4,  then the same error occured...

**Comment by YisuZhou** [comment]
I uninstalled v1.3.0 and installed v1.2.4,  then the same error occured...

**Comment by kartikwar** [comment]
you can make use of the dockerfile given in this repo at https://github.com/SwinTransformer/Swin-Transformer-Semantic-Segmentation/tree/main/docker

**Comment by kartikwar** [comment]
I have added the working installation instructions at https://github.com/kartikwar/Swin-Transformer-Semantic-Segmentation
