### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR what():  CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by JZPeterPan** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#12]
As I ran the Inference for single-gpu testing as written in the README, the inference process stopped at 10/2000 with the following error:
```
Use load_from_local loader
[                              ] 10/2000, 0.9 task/s, elapsed: 11s, ETA:  2161spython-BaseException
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/apis/test.py", line 60, in single_gpu_test
    result = model(return_loss=False, **data)
  File "/home/peter/Applications/anaconda3/envs/swin-seg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/peter/Applications/anaconda3/envs/swin-seg/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/peter/Applications/anaconda3/envs/swin-seg/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/peter/Applications/anaconda3/envs/swin-seg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/peter/Applications/anaconda3/envs/swin-seg/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/base.py", line 124, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/encoder_decoder.py", line 265, in simple_test
    seg_logit = self.inference(img, img_meta, rescale)
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/encoder_decoder.py", line 250, in inference
    seg_logit = self.whole_inference(img, img_meta, rescale)
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/encoder_decoder.py", line 217, in whole_inference
    seg_logit = self.encode_decode(img, img_meta)
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/encoder_decoder.py", line 88, in encode_decode
    out = self._decode_head_forward_test(x, img_metas)
  File "/home/peter/PycharmProjects/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/encoder_decoder.py", line 110, in _decode_head_forward_test
```

I have googled this error (https://github.com/pytorch/pytorch/issues/21819) and the culprits could be too big `batch_size`. 

But the `samples_per_gpu` was set to 1 and I have a GPU with a huge memory of 48GB, and during the inference it gradually took all 48GB till it overflowed. so it must be something wrong with the setting or within the code, but I cannot find it out.

Can you help me to solve it? Thanks in advance.

**Comment by JZPeterPan** [comment]
Solve it by myself:
it seems like pytorch 1.6.0 and cudatoolkit 10.1 are not compatible with cudnn 8.1.0 or higher. As I downgrade my cudnn version to 8.0.5, this problem got solved... it was a very wired bug, tried so many methods to solve it
