### ISSUE TITLE
How can I load an pretrained model to train my dataset with num_cls=2. 

### ISSUE THREAD

**Issue by shanhuhaifeng** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#46]
After I loaded the pretrained model file (namely 'upernet_swin_small_patch4_window7_512x512.pth'), an error was raised as the follow. What is different between my custom dataset with ADE20K is that the num_cls of mine is 2, not 150. So, did the pretrained model only be useful to the ADE? How can I load an pretrained model to train my dataset with num_cls=2. 
Thank you for your help!
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/home/xxx/paper_code2/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/encoder_decoder.py", line 39, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/xxx/paper_code2/Swin-Transformer-Semantic-Segmentation/mmseg/models/segmentors/encoder_decoder.py", line 68, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/xxx/paper_code2/Swin-Transformer-Semantic-Segmentation/mmseg/models/backbones/swin_transformer.py", line 594, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/xxx/paper_code2/Swin-Transformer-Semantic-Segmentation/mmcv_custom/checkpoint.py", line 340, in load_checkpoint
    table_current = model.state_dict()[table_key]
KeyError: 'backbone.layers.0.blocks.0.attn.relative_position_bias_table'

During handling of the above exception, another exception occurred:

**Comment by VV1314** [comment]
This problem also happened to me. Have you handle it?

**Comment by TNA8** [comment]
The pretrained model you used is not Swin-T SSL model. You have to use this one
![screenshot_10](https://user-images.githubusercontent.com/58914448/140478409-ca8723ce-d024-4bb5-a417-c142a0492079.png)
:

**Comment by Lsz-20** [comment]
Have you solved this question？
Are you using swin for segmentation？
