### ISSUE TITLE
question about AssertionError: PascalVOCDataset: 

### ISSUE THREAD

**Issue by yiiiruu** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#6]
Hello, I convert my dataset to VOC format and modify my config file ,then I trained a segment task with "python tools/train.py configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_voc.py --options model.pretrained=../pretrain_models/swin_tiny_patch4_window7_224.pth" on my own datasets,it happened:

Traceback (most recent call last):
  File "tools/train.py", line 163, in <module>
    main()
  File "tools/train.py", line 159, in main
    meta=meta)
  File "/home/ma-user/work/Swin-Transformer-Semantic-Segmentation/mmseg/apis/train.py", line 100, in train_segmentor
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/home/ma-user/work/Swin-Transformer-Semantic-Segmentation/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: PascalVOCDataset: 

I wonder if the code not support VOC format dataset? which kind of dataset do the code support?
thank you!

**Comment by congcongwy51** [comment]
@yr-zh 您好，我想问问您怎么解决的
