### ISSUE TITLE
Error：lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (61, 4))

### ISSUE THREAD

**Issue by skyler9901** [SwinTransformer/Swin-Transformer-Semantic-Segmentation#81]
用swin_tiny_patch4_window7_224.pth预训练权重跑train.py时报错
（环境是pythn3.7 CUDA11.1 pytorch1.8.1 mmcv==1.3.0）
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (61, 4))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (61, 4))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 131, in ParseCodeToTree
    raise e
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 129, in ParseCodeToTree
    ast.parse(code)
  File "/root/miniconda3/envs/myconda/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 61
    sys=<module 'sys' (built-in)>
        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
    main()
  File "tools/train.py", line 99, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/mmcv/utils/config.py", line 458, in dump
    f.write(self.pretty_text)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/mmcv/utils/config.py", line 413, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:61:5: invalid syntax

想请教一下

**Comment by skyler9901** [comment]
i figure it out!

**Comment by skyler9901** [comment]
> 用swin_tiny_patch4_window7_224.pth预训练权重跑train.py时报错 （环境是pythn3.7 CUDA11.1 pytorch1.8.1 mmcv==1.3.0） Traceback (most recent call last): File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree tree = parser_driver.parse_string(code, debug=False) File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string return self.parse_tokens(tokens, debug) File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens if p.addtoken(type, value, (prefix, start)): File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken raise ParseError("bad input", type, value, context) lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (61, 4))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree tree = parser_driver.parse_string(code, debug=False) File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string return self.parse_tokens(tokens, debug) File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens if p.addtoken(type, value, (prefix, start)): File "/root/miniconda3/envs/myconda/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken raise ParseError("bad input", type, value, context) lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (61, 4))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode tree = pytree_utils.ParseCodeToTree(unformatted_source) File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 131, in ParseCodeToTree raise e File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 129, in ParseCodeToTree ast.parse(code) File "/root/miniconda3/envs/myconda/lib/python3.7/ast.py", line 35, in parse return compile(source, filename, mode, PyCF_ONLY_AST) File "", line 61 sys=<module 'sys' (built-in)> ^ SyntaxError: invalid syntax
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "tools/train.py", line 162, in main() File "tools/train.py", line 99, in main cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config))) File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/mmcv/utils/config.py", line 458, in dump f.write(self.pretty_text) File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/mmcv/utils/config.py", line 413, in pretty_text text, _ = FormatCode(text, style_config=yapf_style, verify=True) File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode raise errors.YapfError(errors.FormatErrorMsg(e)) yapf.yapflib.errors.YapfError: :61:5: invalid syntax
> 
> 想请教一下

**Comment by Cemm23333** [comment]
Can you tell me how to solve it ?
